### ISSUE TITLE
.meme command not working

### ISSUE THREAD

**Issue by JGriffin34432** [pedall/g4m3r-wiki#8]
**Problem:** `.meme add` command is not working

**Steps to Reproduce:**
1. First Type `.meme add`
2. Then error appears

![image](https://user-images.githubusercontent.com/32964555/41810219-e8cde30a-76c8-11e8-9dbd-70c9fa7c97a8.png)

**Device:** Windows 10 Home Build 1803

**IGN:** JoshTheGamer632#0017

**Comment by Skillz4Killz** [comment]
Issue moved to [pedall/g4m3r-bot #584](https://github.com/pedall/g4m3r-bot/issues/584) via [**ZenHub**](https://www.zenhub.com/)
